EMAIL_FLOW_RUNS_COLLECTION = "email-flow-runs"

NODE_TYPE_START = "start"
NODE_TYPE_LOAD_THREAD_CONTEXT = "load_thread_context"
NODE_TYPE_READ_KB = "read_kb"
NODE_TYPE_READ_TOOLS = "read_tools"
NODE_TYPE_AI_DEPARTMENT_ROUTER = "ai_department_router"
NODE_TYPE_AI_RECIPIENTS_GENERATOR = "ai_recipients_generator"
NODE_TYPE_GENERATE_EMAIL = "generate_email"
NODE_TYPE_SAVE_GMAIL_DRAFT = "save_gmail_draft"
NODE_TYPE_STOP = "stop"

REPLY_ACTION_MODE_DRAFT = "draft"
REPLY_ACTION_MODE_AUTO_SEND = "auto_send"

AI_ACTION_STATUS_DRAFT_READY = "draft_ready"
AI_ACTION_STATUS_NONE = "none"
AI_ACTION_STATUS_RESOLVED = "resolved"
AI_ACTION_STATUS_FAILED = "failed"
AI_ACTION_STATUS_SUPERSEDED = "superseded"

AI_ACTION_TYPE_DRAFT = "draft"
AI_ACTION_TYPE_DRAFT_FALLBACK = "draft_fallback"

AI_OUTCOME_DRAFT_CREATED = "draft_created"
FINAL_ACTION_TYPE_DRAFT = "draft"

AI_REPLY_MODE_REVIEWED = "reviewed"
AI_REPLY_MODE_AUTO = "auto"

EMAIL_FLOW_REASONING_LLM_MODELS = frozenset({"gpt-5.4", "gpt-5.5"})
EMAIL_TOOLS_DEFAULT_MAX_CALLS = 3
EMAIL_TOOLS_ALLOWED_LLM_MODELS = EMAIL_FLOW_REASONING_LLM_MODELS

EMAIL_ROUTER_MESSAGE_LIMIT = 5
EMAIL_ROUTER_LLM_MAX_RETRIES = 3
EMAIL_ROUTER_LLM_RETRY_DELAY_SECONDS = 1.0
EMAIL_GENERATE_LLM_MAX_RETRIES = 3
EMAIL_GENERATE_LLM_RETRY_DELAY_SECONDS = 1.0
EMAIL_GENERATE_MIN_CONFIDENCE = 0.1
EMAIL_GENERATE_MAX_CONFIDENCE = 1.0
EMAIL_GENERATE_FALLBACK_CONFIDENCE = 0.1
EMAIL_GENERATE_FALLBACK_DRAFT = (
    "Hello there,\n\n"
    "Thank you for your message. A member of our team will review your request "
    "and follow up with you shortly.\n\n"
    "Best regards"
)
EMAIL_TOOLS_HTTP_TIMEOUT_SECONDS = 30.0
EMAIL_TOOLS_LLM_MAX_RETRIES = 3
EMAIL_TOOLS_LLM_RETRY_DELAY_SECONDS = 1.0

RUN_TYPE_SYNC = "sync"
RUN_TYPE_REPROCESS = "reprocess"
RUN_TYPE_PREVIEW = "preview"

FLOW_RUN_STATUS_QUEUED = "queued"
FLOW_RUN_STATUS_RUNNING = "running"
FLOW_RUN_STATUS_COMPLETED = "completed"
FLOW_RUN_STATUS_FAILED = "failed"
FLOW_RUN_STATUS_SKIPPED = "skipped"

NODE_LOG_STATUS_OK = "ok"
NODE_LOG_STATUS_FAILED = "failed"
NODE_LOG_STATUS_SKIPPED = "skipped"

MESSAGE_PROCESSING_STATUS_PENDING = "pending"
MESSAGE_PROCESSING_STATUS_PROCESSING = "processing"
MESSAGE_PROCESSING_STATUS_COMPLETED = "completed"
MESSAGE_PROCESSING_STATUS_FAILED = "failed"
MESSAGE_PROCESSING_STATUS_SKIPPED = "skipped"

DEFAULT_THREAD_MESSAGE_LIMIT = 10
COMPRESSED_QUERY_MAX_CHARS = 500
FLOW_PREVIEW_RUN_PREFIX = "preview"

EMAIL_COMPRESS_LLM_MODEL = "gpt-4.1-mini"
EMAIL_COMPRESS_MAX_RETRIES = 3
EMAIL_COMPRESS_PER_MESSAGE_CHAR_CAP = 12_000
EMAIL_COMPRESS_LLM_TEMPERATURE = 0.2
EMAIL_COMPRESS_RETRY_DELAY_SECONDS = 1.0
