ELYSIUM_ATLAS_AGENT_CONFIG_DATA = {
    "agent_init_config": {
        "agent_name": "my-agent",
        "owner_user_id":None,
        "agent_aliases":[],
        "agent_icon":None,
        "base_url":None,
        "organization_name":None,
        "llm_model":"gpt-4o-mini",
        "welcome_message":"Hello, I am your AI assistant. How can I help you today?",
        "placeholder_text":"Enter your message here...",
        "primary_color":"#000000",
        "secondary_color":"#ffffff",
        "text_color":"#000000",
        "quick_prompts":[],
        "footer":None,
        "agent_personality":None,
        "agent_status":"inactive",
        "agent_current_task": "initializing",
    },
    "agent_task_progress": {
        "initializing": 0,
        "Indexing Links": 5,
        "Links Indexed": 25,
        "Indexing Files": 30,
        "Files Indexed": 50,
        "Indexing Custom Knowledge": 75,
        "Custom Knowledge Indexed": 90,
        "running": 100,
    },
}