ELYSIUM_ATLAS_AGENT_CONFIG_DATA = {
    "agent_init_config": {
        "agent_name": "my-agent",
        "owner_user_id":None,
        "agent_aliases":[],
        "agent_icon":None,
        "base_url":None,
        "organization_name":None,
        "llm_model":"gpt-4o-mini",
        "welcome_message":"Hello, I am your AI assistant. How can I help you today?",
        "placeholder_text":"Enter your message here...",
        "primary_color":"#000000",
        "secondary_color":"#ffffff",
        "text_color":"#000000",
        "quick_prompts":[],
        "footer":None,
        "agent_status":"inactive",
        "agent_current_task": "initializing",
        "system_prompt":"You are a helpful assistant.",
        "temperature":0.5,
    },
    "agent_task_progress": {
        "initializing": 0,
        "updating agent metadata": 2,
        "Indexing Links": 5,
        "Links Indexed": 25,
        "Indexing Files": 30,
        "Files Indexed": 50,
        "Indexing Custom Knowledge": 75,
        "Custom Knowledge Indexed": 90,
        "running": 100,
    },
    "chat_session_init_config": {
        "chat_session_id": None,
        "created_at": None,
        "last_message_at": None,
        "agent_name": None,
        "agent_id": None,
        "channel": None,
        "status": "active",
        "visitor_at": None,
        "visitor_online": False,
        "source": None,
    },
}