"""Runtime constants for human handover."""

HANDOVER_TRIGGER_MODEL = "gpt-4.1-mini"
HANDOVER_CHAT_HISTORY_LIMIT = 100

HANDOVER_STATUS_REQUESTED = "requested"
HANDOVER_STATUS_ASSIGNED = "assigned"

CONTACT_STATUS_PENDING = "pending"
CONTACT_STATUS_PROVIDED = "provided"
CONTACT_STATUS_DECLINED = "declined"

HANDOVER_WAITING_MESSAGE = (
    "Your request to speak with a team member has been registered. "
    "Someone will join as soon as possible."
)

VISITOR_TAKEOVER_STARTED_MESSAGE = "You are now in conversation with {name}."
VISITOR_TAKEOVER_STARTED_FALLBACK_NAME = "a team member"

MAX_HANDOVER_CONTACT_NAME_LENGTH = 200
MAX_HANDOVER_CONTACT_EMAIL_LENGTH = 320

ERR_HANDOVER_SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
ERR_HANDOVER_NOT_REQUESTED = "HANDOVER_NOT_REQUESTED"
ERR_HANDOVER_CONTACT_ALREADY_RESOLVED = "CONTACT_ALREADY_RESOLVED"
ERR_HANDOVER_INVALID_NAME = "INVALID_NAME"
ERR_HANDOVER_INVALID_EMAIL = "INVALID_EMAIL"
